// ── Exercise / Program constants ──────────────────────────────
const EX_CATEGORIES = ['Tren inferior','Tren superior','Core','Cardio / Metabólico','Técnico / Táctico','Movilidad / Elongación','Potencia / Pliometría','Otro'];
const BLOCK_TYPES = [
  {id:'warmup',    label:'WARM-UP',    color:'#0891b2'},
  {id:'strength',  label:'STRENGTH',   color:'#7c3aed'},
  {id:'power',     label:'POWER',      color:'#ea580c'},
  {id:'plyo',      label:'PLYO',       color:'#db2777'},
  {id:'speed',     label:'SPEED',      color:'#dc2626'},
  {id:'cardio',    label:'CARDIO',     color:'#16a34a'},
  {id:'mobility',  label:'MOBILITY',   color:'#8b5cf6'},
  {id:'preventive',label:'PREVENTIVE', color:'#0d9488'},
  {id:'tactical',  label:'TACTICAL',   color:'#2563eb'},
  {id:'cooldown',  label:'COOL-DOWN',  color:'#475569'},
  {id:'custom',    label:'BLOQUE',     color:'#d97706'},
];
function blockTypeInfo(id){return BLOCK_TYPES.find(b=>b.id===id)||BLOCK_TYPES[BLOCK_TYPES.length-1];}
function formatSetDisplay(s){
  if(!s) return '—';
  const type=s.type||'reps';
  const val=type==='time'?(s.time?s.time+'s':''):(s.reps||'');
  const w=s.weight?s.weight+'kg':'';
  const mod=s.rir?'RiR'+s.rir:(s.pct?s.pct+'%RM':'');
  const parts=[val,w,mod].filter(Boolean);
  return parts.length?parts.join(' · '):'—';
}
function formatAthleteSetStr(sets){
  if(!sets.length) return '';
  const strs=sets.map(s=>formatSetDisplay(s)).filter(s=>s!=='—');
  if(!strs.length) return '';
  const allSame=strs.every(s=>s===strs[0]);
  return allSame?`${sets.length} × ${strs[0]}`:strs.join(' → ');
}

// ── Default exercise library (always visible in Global tab) ───
const DEFAULT_EXERCISES = {
  // ── Tren inferior ──────────────────────────────────────────────
  'def_sq':      {name:'Sentadilla con barra',            category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=QmZAiBqPvZw'},
  'def_fsq':     {name:'Sentadilla frontal',              category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=_mFuKrZ-wZw'},
  'def_airsq':   {name:'Sentadilla al aire',              category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=rMvwVtlqjTE'},
  'def_rdl':     {name:'Peso muerto rumano',              category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=fOEgeUvZjV0'},
  'def_leg':     {name:'Prensa de piernas',               category:'Tren inferior'},
  'def_lunge':   {name:'Estocadas caminando',             category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=DlhojghkaQ0'},
  'def_stepup':  {name:'Step-up en caja',                 category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=5qjqDHOUh-A'},
  'def_nordic':  {name:'Nordic curl',                     category:'Tren inferior'},
  'def_hipth':   {name:'Hip thrust con barra',            category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=aweBS7K71l8'},
  // ── Tren superior ─────────────────────────────────────────────
  'def_bp':      {name:'Press de banca plano',            category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=SCVCLChPQFY'},
  'def_ohp':     {name:'Press militar con barra',         category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=5yWaNOvgFCM'},
  'def_pp':      {name:'Push press',                      category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=iaBVSJm78ko'},
  'def_dbpp':    {name:'Push press con mancuernas',       category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=4tCaD42ghlc'},
  'def_pushup':  {name:'Flexiones de brazo',              category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=0pkjOk0EiAk'},
  'def_row':     {name:'Remo con barra',                  category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=smyvaY7dtx4'},
  'def_pull':    {name:'Dominadas / Pull-up',             category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=aAggnpPyR6E'},
  'def_dips':    {name:'Fondos en paralelas',             category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=ugm2aLH2yzs'},
  'def_curl':    {name:'Curl de bíceps con mancuerna',    category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=HnHuhf4hEWY'},
  'def_tri':     {name:'Extensión de tríceps en polea',   category:'Tren superior'},
  // ── Core ──────────────────────────────────────────────────────
  'def_plank':   {name:'Plancha isométrica',              category:'Core',                   videoUrl:'https://www.youtube.com/shorts/O83fmDwTYpg'},
  'def_dead':    {name:'Peso muerto convencional',        category:'Core'},
  'def_ab':      {name:'Abdominales en suelo',            category:'Core'},
  'def_russ':    {name:'Russian twist',                   category:'Core'},
  'def_tgu':     {name:'Turkish get-up con mancuerna',    category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=saYKvqSscuY'},
  // ── Cardio / Metabólico ───────────────────────────────────────
  'def_burpee':  {name:'Burpee',                          category:'Cardio / Metabólico',    videoUrl:'https://www.youtube.com/watch?v=auBLPXO8Fww'},
  'def_sprint':  {name:'Sprint 30m',                      category:'Cardio / Metabólico'},
  'def_rondo':   {name:'Rondo 5v2',                       category:'Cardio / Metabólico'},
  'def_hitt':    {name:'HIIT 30-30',                      category:'Cardio / Metabólico'},
  // ── Potencia / Pliometría ─────────────────────────────────────
  'def_clean':   {name:'Cargada (Clean)',                  category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=Ty14ogq_Vok'},
  'def_hpc':     {name:'Cargada desde colgado (Hang Power Clean)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=0aP3tgKZcHQ'},
  'def_dbclean': {name:'Cargada con mancuernas (DB Clean)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=SYxObzJ3gn0'},
  'def_mbclean': {name:'Cargada con balón medicinal',     category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=KVGhkHSrDJo'},
  'def_cj':      {name:'Cargada y envión (Clean & Jerk)', category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=PjY1rH4_MOA'},
  'def_snatch':  {name:'Arranque (Snatch)',                category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=GhxhiehJcQY'},
  'def_psnatch': {name:'Arranque de fuerza (Power Snatch)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=TL8SMp7RdXQ'},
  'def_hps':     {name:'Arranque desde colgado (Hang Power Snatch)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=-mLzQdVAwlw'},
  'def_dbsnatch':{name:'Arranque con mancuerna (DB Power Snatch)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=3mlhF3dptAo'},
  'def_kbsnatch':{name:'Arranque con pesa rusa (KB Snatch)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=Pm-b2XFeABA'},
  'def_sjerk':   {name:'Envión de tijera (Split Jerk)',   category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=GUDkOtraHHY'},
  'def_thr':     {name:'Thruster',                        category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=L219ltL15zk'},
  'def_dbthr':   {name:'Thruster con mancuernas',         category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=u3wKkZjE8QM'},
  'def_kbswing': {name:'Swing con pesa rusa (KB Swing)',  category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=mKDIuUbH94Q'},
  'def_slamball':{name:'Lanzamiento de balón (Slam Ball)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=k9W6g9LvXDI'},
  'def_cmj':     {name:'Salto CMJ',                       category:'Potencia / Pliometría'},
  'def_box':     {name:'Box jump',                        category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=NBY9-kTuHEk'},
  'def_bbjo':    {name:'Burpee box jump over',            category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=GLktGkmcvWE'},
  'def_drop':    {name:'Drop jump',                       category:'Potencia / Pliometría'},
  // ── Movilidad / Elongación ────────────────────────────────────
  'def_foam':    {name:'Foam roller — MMII',              category:'Movilidad / Elongación'},
  'def_mob':     {name:'Movilidad articular guiada',      category:'Movilidad / Elongación'},
  'def_elon':    {name:'Elongación isquiotibial',         category:'Movilidad / Elongación'},
  // ── Nuevos ────────────────────────────────────────────────────
  'def_ringrow': {name:'Remo en anillas (Ring Row)',                    category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=sEAOZc77wk8'},
  'def_dbohsq':  {name:'Sentadilla sobre cabeza con mancuerna (OHS)',  category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=azumEfnk-GI'},
  'def_absit':   {name:'Abdominales con AbMat (AbMat Sit-Up)',         category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=VIZX2Ru9qU8'},
  'def_hpccpj':  {name:'Cargada desde colgado y envión (HPC + Push Jerk)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=8IYt7AtP8BI'},
  'def_zercher': {name:'Sentadilla Zercher (Zercher Squat)',           category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=nwx6Ip7hd3I'},
  'def_lsit':    {name:'L-Sit colgado (Hanging L-Sit)',               category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=WHi1bvZLwlw'},
  'def_ctb':     {name:'Dominada pecho a la barra (Chest-to-Bar)',    category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=xf69XHAs5w8'},
  'def_broadjmp':{name:'Salto en largo (Broad Jump)',                 category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=AOkmLTD8J24'},
  'def_cqsjmp':  {name:'Salto concéntrico en cuarto sentadilla',      category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=jDmNzL_jctc'},
  'def_depthdrop':{name:'Caída de profundidad (Depth Drop)',          category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=GZLyZCqF8BQ'},
  'def_depthjmp':{name:'Salto de profundidad (Depth Jump)',           category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=GeN0S3XCZnM'},
  'def_pausebox':{name:'Salto al cajón con pausa (Pause Box Jump)',   category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=OupSuT2VFTk'},
  'def_seatedbox':{name:'Salto al cajón sentado (Seated Box Jump)',   category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=yhBwqIvXHgw'},
  'def_seatedvj':{name:'Salto vertical sentado (Seated Vertical Jump)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=3x_mz9qztMI'},
  'def_sqboxjmp':{name:'Salto al cajón desde sentadilla (Squat Box Jump)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=sUK1NDgjIcg'},
  'def_vertjmp': {name:'Salto vertical (Vertical Jump)',              category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=85FvMEHl3Vo'},
  'def_bblunge':   {name:'Estocada con barra (Barbell Lunge)',        category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=jfE5UTunYik'},
  'def_tricext':   {name:'Copa de tríceps (Tricep Extension)',        category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=fk_aTgTYaZk'},
  'def_latraise':  {name:'Elevaciones laterales (Lateral Raises)',    category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=uWz-QvZW3oM'},
  'def_abwheel':   {name:'Rueda abdominal (Ab Wheel)',                category:'Core',                   videoUrl:'https://www.youtube.com/shorts/kbXRnap6mV0'},
  'def_mountclimb':{name:'Escaladores (Mountain Climbers)',           category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=kLh-uczlPLg'},
  'def_jumprope':  {name:'Salto a la comba (Jump Rope)',              category:'Cardio / Metabólico',    videoUrl:'https://www.youtube.com/shorts/jqtzzVesUOo'},
  'def_spinning':  {name:'Spinning',                                  category:'Cardio / Metabólico',    videoUrl:'https://www.youtube.com/shorts/zKPFQUGd3LA'},
  'def_dbrdl':     {name:'Peso muerto rumano con mancuerna (DB RDL)',            category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=xzwZejo2zo8'},
  'def_dblunge':   {name:'Estocada con mancuerna (DB Lunge)',                    category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=lf4gJgKyLpI'},
  'def_goblet':    {name:'Sentadilla goblet con mancuerna (Goblet Squat)',        category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=QHKe84ZSTrg'},
  'def_dbsldl':    {name:'Peso muerto rumano a una pierna con mancuerna (B-Stance RDL)', category:'Tren inferior', videoUrl:'https://www.youtube.com/watch?v=74rHsyE1_3A'},
  'def_nordicdrop':{name:'Caída nórdica (Nordic Drops)',                         category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=r0M7YB0by38'},
  'def_dbbp':      {name:'Press de banca con mancuernas (DB Bench Press)',        category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=ZaDlbm8E8Tg'},
  'def_dbohp':     {name:'Press militar con mancuernas (DB Military Press)',      category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/UbB6gwHiV7g'},
  'def_dbrow':     {name:'Remo con mancuerna (DB Row)',                           category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=Wj8k-7zGs0I'},
  'def_frontraise':{name:'Elevación frontal con mancuerna (Front Raise)',         category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=byzMcajjyHg'},
  'def_zottman':   {name:'Curl Zottman (Zottman Curl)',                           category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=equAAU1Bv0E'},
  'def_seatedohp': {name:'Press de hombros sentado con mancuerna (Seated DB OHP)', category:'Tren superior',        videoUrl:'https://www.youtube.com/watch?v=OYTDIA0dJSs'},
  'def_arnold':    {name:'Press Arnold sentado con mancuerna (Arnold Press)',      category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=23UPrYjKsPE'},
  'def_dbbentrow': {name:'Remo con mancuernas inclinado (Dual DB Bent Over Row)', category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=3DpTiQEWwMk'},
  'def_gorillarow':{name:'Remo gorilla con pesas rusas (KB Gorilla Row)',          category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=8_k47yprO10'},
  'def_cablecurl':  {name:'Curl de bíceps en polea (Face Away Cable Curl)',        category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=o2fTdaAtRmY'},
  'def_snowangel':  {name:'Ángel de nieve a flexión (Snow Angel to Push Up)',      category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=rIJiD2SoDQ0'},
  'def_cableohext': {name:'Extensión de tríceps sobre la cabeza en polea (Cable Overhead Extension)', category:'Tren superior', videoUrl:'https://www.youtube.com/watch?v=s4q6JIzm3ZU'},
  'def_chestdips':  {name:'Fondos de pecho (Chest Dips)',                          category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=ugm2aLH2yzs'},
  'def_cablelat':   {name:'Vuelos laterales en polea (Cable Lateral Raise)',        category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=x9pOAaIa6dI'},
  'def_ropecurl':   {name:'Curl de bíceps con cuerda en polea (Rope Cable Curl)',  category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=yKziPg6Jq7c'},
  'def_facepull':   {name:'Tirón al rostro en polea (Face Pull)',                  category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=RBWjJqHzd7c'},
  'def_cablepush':  {name:'Empuje de tríceps barra recta en polea (Cable Pushdown)', category:'Tren superior',        videoUrl:'https://www.youtube.com/watch?v=NoQYLw75WK4'},
  'def_kneelatlpd': {name:'Jalón dorsal a un brazo arrodillado (Half Kneeling Lat Pulldown)', category:'Tren superior', videoUrl:'https://www.youtube.com/watch?v=UvY91EwcS8U'},
  'def_strictpull': {name:'Dominada estricta pronada (Pronated Strict Pull Up)',   category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=a8OaMNvz3WA'},
  'def_hrpushup':   {name:'Flexión con liberación de manos (Hand Release Push Up)', category:'Tren superior',         videoUrl:'https://www.youtube.com/watch?v=1bt20MAuC10'},
  'def_toetouches': {name:'Toque de punteras alterno (Alternating Toe Touches)',   category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=bQxCihmuF0c'},
  'def_calfpump':   {name:'Bombeos de pantorrilla (Calf Pumps)',                   category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=vzp-AuFqexY'},
  'def_squatstand': {name:'Sentadilla a extensión (Squat to Stand)',               category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=wC2FCdoHm9M'},
  'def_dogcobra':   {name:'Perro boca abajo a cobra con rotación (Down Dog to Cobra)', category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=hZlUhl3ooKI'},
  'def_beststretch':{name:'Rotación de estiramiento (Best Stretch Rotations)',     category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=nerm7uqCE5M'},
  'def_staggerrdl': {name:'Calentamiento RDL escalonado (Staggered Stance RDL Warm Up)', category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=PaGvnbo1LWU'},
  'def_revlungerot':{name:'Estocada reversa con rotación (Reverse Lunge Rotations)', category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=c-s2RHsnUQU'},
  'def_crosscabletri':{name:'Empuje de tríceps en poleas cruzadas',                 category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=22OVa6lMeQE'},
  'def_kickbacktri': {name:'Patada de tríceps en polea',                            category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=3LHpomvtp60'},
  'def_shelc':       {name:'Flexión de piernas elevado (SHELC)',                    category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=7WvKMkFk-4M'},
  'def_invrow':      {name:'Remo invertido',                                        category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=7lD0se-8HtQ'},
  'def_seatedcabrow':{name:'Remo en polea baja sentado',                            category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=E4ygp6bITbk'},
  'def_catcow':      {name:'Postura gato-vaca (Cat-Cow)',                           category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=FF11_7XfIPk'},
  'def_ropetripush': {name:'Empuje de tríceps en polea alta con cuerda (Rope Pushdown)', category:'Tren superior',    videoUrl:'https://www.youtube.com/watch?v=KymuKtiZgSw'},
  'def_threadneedle':{name:'Enhebrar la aguja (Thread the Needle)',                 category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=MfjH6I9vDjQ'},
  'def_archerpush': {name:'Flexión de arquero (Archer Push Up)',                   category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=8Lp075Q3BGg'},
  'def_latpull':    {name:'Jalón al pecho (Lat Pull Down)',                        category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=SZuLHOEx4N0'},
  'def_splitchop':  {name:'Chop en posición de estocada (Split Stance Chop)',      category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=1k-WQRew_Jg'},
  'def_multiplunge':{name:'Estocada multiplanar (Multiplanar Lunge)',              category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=9g41K93MnVw'},
  'def_suitcasedl': {name:'Peso muerto tipo maleta (Suitcase Deadlift)',           category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=Kqap3q36t20'},
  'def_hkneelift':  {name:'Levantamiento en media rodilla (Half Kneeling Lift)',   category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=7l6SkKrd9iE'},
  'def_pullthrough':{name:'Pull through (Tracción entre piernas)',                 category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=vtdq0rcCLtE'},
  'def_defrevlunge':{name:'Estocada reversa con déficit (Deficit Reverse Lunge)',  category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=a_xhqPezYg8'},
  'def_grasshopper':{name:'Flexión de saltamontes (Grasshopper Push Up)',          category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=jXeWbisQXTs'},
  'def_spidercurl': {name:'Curl spiderman (Spiderman Hammer Curl)',                category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=JsTLU-u2uOY'},
  'def_plankjump':  {name:'Salto en plancha alterno (Alternating Plank Jump)',     category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=u6mLiasODxg'},
  'def_rolloutpush':{name:'Flexión con desplazamiento (Rollout Push Up)',          category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=TfsvytZDjf0'},
  'def_pikepush':   {name:'Flexión en V (Pike Push Up)',                           category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=6NZpP-QU8yE'},
  'def_inclinepush':{name:'Flexión inclinada (Incline Push Up)',                   category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=84citUerNPs'},
  'def_landminethr':{name:'Thruster en landmine (Landmine Thruster)',              category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=p_uesP_uCi0'},
  'def_offsetsq':   {name:'Sentadilla desplazada en landmine (Offset Squat)',      category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=WHcM8T3xfvo'},
  'def_wallknee':   {name:'Rodilla al pecho con apoyo en pared',                  category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/watch?v=At9lrvZT7Po'},
  'def_bandlungepr':{name:'Estocada y press con banda',                           category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=N-4nV5Lht68'},
  'def_lmhacksq':   {name:'Sentadilla hack en landmine',                          category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=6U2b7btD-uM'},
  'def_lmrainbow':  {name:'Arcoíris en landmine',                                 category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=DZHki7yVkvk'},
  'def_lmdeadbug':  {name:'Dead bug anclado a landmine',                          category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=YAMZwQor8E8'},
  'def_lmcurl':     {name:'Curl de bíceps agarre mixto en landmine',              category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=iXezXAa50Ks'},
  'def_lmbearcrawl':{name:'Caminata de oso en landmine',                          category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=RWxK7BpGLh0'},
  'def_lm2handrow': {name:'Remo con dos manos en landmine',                       category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=Kvwbx2oJPGo'},
  'def_lmfloorpr':  {name:'Press de suelo a un brazo en landmine',                category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=G0ghWie674s'},
  'def_lmsurfsq':   {name:'Sentadilla de surfista desfasada en landmine',         category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=DREWSOsgzcc'},
  'def_lmzpress':   {name:'Z press a un brazo en landmine',                       category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=0CLEzEaT6sA'},
  'def_jacknife':   {name:'Jacknife',                                             category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=-jLFJPw0fLE'},
  'def_tpushup':    {name:'Push up con rotación en T (T-Roll Push Up)',           category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=vuroSsyp1f8'},
  'def_trxsq':      {name:'Sentadilla profunda en TRX (TRX Deep Squat)',          category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=_P_ei1kOQ7M'},
  'def_bbrollout':  {name:'Rollout con barra (Barbell Rollout)',                  category:'Core',                   videoUrl:'https://www.youtube.com/shorts/4aQlcypBWEw'},
  'def_trxpushup':  {name:'Push up en TRX (Suspension Trainer Push Up)',          category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=y62IItfqhGI'},
  'def_trxpike':    {name:'V invertida en TRX (TRX Assisted Pike)',               category:'Core',                   videoUrl:'https://www.youtube.com/watch?v=FAgkMv5V36c'},
  'def_trxtri':     {name:'Tríceps en TRX (TRX Triceps Press)',                   category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=9F7bI_VAPeM'},
  'def_db1legrdl':  {name:'Peso muerto rumano unilateral con mancuerna (DB One-Leg RDL)', category:'Tren inferior', videoUrl:'https://www.youtube.com/watch?v=JNivi_Nnj7E'},
  'def_1arm1legbp': {name:'Press de banca unilateral y una pierna (DB One-Arm One-Leg Bench Press)', category:'Tren superior', videoUrl:'https://www.youtube.com/watch?v=f1aW-UjdORY'},
  'def_splitsqjmp': {name:'Salto en sentadilla split reactiva con mancuerna (DB Reactive Split Squat Jump)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=VsihAY8G4Lc'},
  'def_hkslam':     {name:'Slam en medio arrodillado (MB Half Kneel Around the World Slam)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=Np7qbnay_ng'},
  'def_fsqbox':     {name:'Sentadilla frontal al cajón (Front Squat To Low Box)',  category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=B8qk-y0DMGU'},
  'def_floorpress': {name:'Press de banca en suelo (Floor Press)',                 category:'Tren superior',          videoUrl:'https://www.youtube.com/watch?v=fNxz1vjSAdM'},
  'def_sumodl':     {name:'Peso muerto sumo (Sumo Deadlift)',                      category:'Tren inferior',          videoUrl:'https://www.youtube.com/watch?v=_xVffXKR1V0'},
  // ── Velocidad / Agilidad ──────────────────────────────────────
  'def_8conedrill': {name:'Drill de 8 conos (8 Cone Snake Drill)',                category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/shorts/Jmunmr5ocgo'},
  'def_4conechase': {name:'Persecución 4 conos (4 Cone Chaser)',                  category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/shorts/PJKGoVPQMB8'},
  'def_ydrill':     {name:'Drill en Y reactivo (Reactive Y-Drill)',               category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=gQx0yE60bRM'},
  'def_lowskip':    {name:'Skipping lineal bajo (Linear Ankling, Low)',           category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=t3NjSiyupIM'},
  'def_highskip':   {name:'Skipping lineal alto (Linear Ankling, High)',          category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=HZyri4vmo0w'},
  'def_lowsrl':     {name:'Piernas rectas baja (Straight Leg Run, Low)',          category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=2mPK3FFonIA'},
  'def_highsrl':    {name:'Piernas rectas alta (Straight Leg Run, High)',         category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=DYOGDqJKeHE'},
  'def_linaskip':   {name:'A-Skips lineales (Linear A-Skips)',                   category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=Fbo32-7Uo6U'},
  'def_linbskip':   {name:'B-Skips lineales (Linear B-Skips)',                   category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=dtd9RBo-RHw'},
  'def_lataskip':   {name:'A-Skips laterales (Lateral A-Skips)',                 category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=U9dXDVE8t1E'},
  'def_staggersrt': {name:'Salida en posición escalonada (Stagger Stance Starts)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=8adSqe635uU'},
  'def_hklinsrt':   {name:'Salida en media rodilla lineal (Linear Half Kneel Starts)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=FGIFiJxx4-w'},
  'def_fallsrt':    {name:'Salida en caída (Falling Starts)',                    category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=RM7nUBcydNs'},
  'def_hklatsrt':   {name:'Salida en media rodilla lateral (Lateral Half Kneel Starts)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=_4BxHrr803Y'},
  'def_hplanksrt':  {name:'Salida en plancha alta (High Plank Starts)',          category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=jD2fl-iGGic'},
  'def_pronesrt':   {name:'Salida de flexión en prono (Prone Push-Up Start)',    category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=15ssS3jFsas'},
  'def_supinesrt':  {name:'Salida con giro en supino (Supine Roll Over Starts)', category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=zX8xrV4vxpQ'},
  'def_reactprone': {name:'Salida de flexión en prono reactiva (Reactive Prone Push-Up Start)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=FpWBTa2di88'},
  'def_reacthkchase':{name:'Persecución en media rodilla lateral reactiva (Reactive Lateral HK Chase & Tag)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=72Wi2WrNYaw'},
  'def_lowpogo':    {name:'Saltos pogo bajos (Low Pogo Jumps)',                  category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=aq_V6XNI2fA'},
  'def_linearjmp':  {name:'Saltos en línea lineales (Linear Line Jumps)',        category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=EsjcomS9e9g'},
  'def_lateraljmp': {name:'Saltos en línea laterales (Lateral Line Jumps)',      category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=PpGWKKfZeMU'},
  'def_mirrordrill':{name:'Espejo con aceleración (Mirror Drill to Acceleration)', category:'Velocidad / Agilidad',  videoUrl:'https://www.youtube.com/watch?v=fcxXZIP5vHQ'},
  'def_wicketdrill':{name:'Drill de vallas (Wicket Drill w Build Up)',            category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=BT4_-ShPQ-M'},
  'def_cursplgr':   {name:'Sprint en curva radio largo - salida media rodilla (Curved Sprint Large Radius)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=E6cbx8xw-BU'},
  'def_cursplmr':   {name:'Sprint en curva radio medio - salida media rodilla (Curved Sprint Medium Radius HK)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=fgKkZKKch7M'},
  'def_curspsmrst': {name:'Sprint en curva radio pequeño - salida escalonada (Curved Sprint Small Radius Stagger)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=yevFiLdmgZo'},
  'def_curspmmrst': {name:'Sprint en curva radio medio - salida escalonada (Curved Sprint Medium Radius Stagger)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=SLS9k7qcrnU'},
  'def_cuspsmrbi':  {name:'Sprint en curva radio pequeño - salida atlética (Curved Sprint Small Radius Bilateral)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=jYHf3hsj9Sk'},
  'def_hklatshufspr':{name:'Salida media rodilla a desplazamiento lateral y sprint (HK Start to Lateral Shuffle to Sprint)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=FJ8qCqGAKZM'},
  'def_pogo45fwd':  {name:'Saltos pogo 45° adelante (45-Degree Pogo Jumps FWD)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=GItiEDUjXzg'},
  'def_pogo45rev':  {name:'Saltos pogo 45° atrás (45-Degree Pogo Jumps REV)',    category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=lH-8x0HiOxI'},
  'def_linlowrev':  {name:'Saltos pogo lineales bajos atrás (Linear Low Pogo REV)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=mn4mJ4CKovc'},
  'def_linlowfwd':  {name:'Saltos pogo lineales bajos adelante (Linear Low Pogo FWD)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=2RMa79Zb0Ws'},
  'def_linhighrev': {name:'Saltos pogo lineales altos atrás (Linear High Pogo REV)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=0Q_hO88MeQQ'},
  'def_linhighfwd': {name:'Saltos pogo lineales altos adelante (Linear High Pogo FWD)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=CfHqG7xinDA'},
  'def_latlowl':    {name:'Saltos pogo laterales bajos izquierda (Lateral Low Pogo L)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=u9g4cqSYR_g'},
  'def_latlowr':    {name:'Saltos pogo laterales bajos derecha (Lateral Low Pogo R)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=kz1kgCKq2BU'},
  'def_lathighr':   {name:'Saltos pogo laterales altos derecha (Lateral High Pogo R)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=fardIahYr9c'},
  'def_lathighl':   {name:'Saltos pogo laterales altos izquierda (Lateral High Pogo L)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=n0_4L_tBzK4'},
  'def_sledmarchfx':{name:'Marcha con trineo - brazos flexionados (Sled March Arms Flexed)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=VBg7iQKIFko'},
  'def_sledmarchex':{name:'Marcha con trineo - brazos extendidos (Sled March Arms Extended)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=LOH1Y2QSLho'},
  'def_wallmarch':  {name:'Drill de pared - marcha (Wall Drill Marching)',        category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=-9YdQjn5loE'},
  'def_wallsingle': {name:'Drill de pared - simples (Wall Drill Singles)',        category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=p9RAqt1z4zk'},
  'def_walldouble': {name:'Drill de pared - dobles (Wall Drill Doubles)',         category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=8axJuCDqQYQ'},
  'def_walltriple': {name:'Drill de pared - triples (Wall Drill Triples)',        category:'Velocidad / Agilidad',   videoUrl:'https://www.youtube.com/watch?v=DetGzg4IylA'},
  'def_walllunge':  {name:'Drill de pared - estocada a empuje de rodilla (Wall Drill Lunge to Knee Drive)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=tKY4iPr6tcE'},
  'def_sledpushex': {name:'Empuje de trineo - brazos extendidos (Sled Push Arms Extended)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=g3Pw_v0N730'},
  'def_sledpushfx': {name:'Empuje de trineo - brazos flexionados (Sled Push Arms Flexed)', category:'Velocidad / Agilidad', videoUrl:'https://www.youtube.com/watch?v=54c39qsRTvo'},
  'def_slsnapdown': {name:'Snap down a una pierna (SL Snap Down)',                category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=21efCYs5n4g'},
  'def_snapdownvj': {name:'Snap down a salto vertical con pausa (Snap Down to VJ w Pause)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=32rohMJ9_XE'},
  'def_sllathopm':  {name:'Saltos laterales a una pierna - misma (SL Lateral Hops Same Leg)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=ZPhxKdLoweU'},
  'def_slhopfwd':   {name:'Saltos extensivos adelante a una pierna (SL FWD Extensive Hops)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=EM2m1TEfJkI'},
  'def_slhoprev':   {name:'Saltos extensivos atrás a una pierna (SL REV Extensive Hops)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=An6cWJ-p0Ns'},
  'def_storkwalk':  {name:'Caminata de cigüeña adelante con pausa (FWD Stork Walks w Pause)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=22VtGZkfwPY'},
  'def_slrothop':   {name:'Saltos en el lugar con rotación a una pierna (SL Rotational In-Place Quarter Hops)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=mVxiEIMayek'},
  'def_sljumpdbl':  {name:'Salto a una pierna con aterrizaje bipodal (SL Jump to DBL Leg Landing)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=HzkbrBLtUJw'},
  'def_hkbroadjmp': {name:'Salto largo desde media rodilla a aterrizaje bipodal (HK Broad Jump to DBL Landing)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=0Xo0bnnXLAI'},
  'def_broadreset': {name:'Salto largo con reinicio (Broad Jump w Reset)',        category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=mcDoCgxDsvg'},
  'def_triplebrjmp':{name:'Triple salto largo continuo (Triple Broad Jump)',      category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=kkQ0qohNt9s'},
  'def_linboundpau':{name:'Saltos alternos lineales con pausa (Linear Bounds w Pause)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=WUZ96zDSfUg'},
  'def_linbound':   {name:'Saltos alternos lineales (Linear Bounds)',              category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=nGhyUeS7Dic'},
  'def_latboundpau':{name:'Saltos alternos laterales con pausa (Lateral Bounds w Pause)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=7M5qnuBuVB4'},
  'def_latboundqr': {name:'Saltos alternos laterales con respuesta rápida (Lateral Bounds w Quick Response)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=BP2p0gqmfew'},
  'def_latboundapu':{name:'Saltos alternos laterales ascendentes con pausa (Lateral Bounds Ascending w Pause)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=iSGQqwexA9s'},
  'def_latboundaqr':{name:'Saltos alternos laterales ascendentes con respuesta rápida (Lateral Bounds Ascending QR)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=zo0E2X9Pvts'},
  'def_45boundpau': {name:'Saltos alternos 45° con pausa (45-Degree Bounds w Pause)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=vBCYRcdSlYQ'},
  'def_45boundqr':  {name:'Saltos alternos 45° con respuesta rápida (45-Degree Bounds w Quick Response)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=xQURj8XBA2M'},
  'def_combobndbi': {name:'Combo saltos alternos lineales a aterrizaje bipodal (Combo Linear Bound to Bilateral Landing)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=rSDob8ibBX4'},
  'def_combobndrot':{name:'Combo saltos alternos lineales a rotacionales (Combo Linear to Rotational)', category:'Potencia / Pliometría', videoUrl:'https://www.youtube.com/watch?v=9Roz8FnWoNs'},
  'def_snapdownfnd':{name:'Snap downs bipedales basales (Foundation Snap Downs)', category:'Potencia / Pliometría',  videoUrl:'https://www.youtube.com/watch?v=ryezhSIWHBw'},
  // ── Core — TGU / Windmill / Carry ─────────────────────────────
  'def_tguhalfsu':      {name:'1/2 Levantamiento Turco (TGU Sit Up to Hip Lift)',                        category:'Core',             videoUrl:'https://www.youtube.com/watch?v=YWY4BYm6a3M'},
  'def_kbwindmill':     {name:'Windmill con pesa rusa (KB Windmill)',                                     category:'Core',             videoUrl:'https://www.youtube.com/watch?v=y8zvXKMKufo'},
  'def_birddogrow':     {name:'Remo en superman (Bird Dog Row)',                                          category:'Core',             videoUrl:'https://www.youtube.com/watch?v=gwglOcD-kvA'},
  'def_1armsitup':      {name:'Sit-Up a un Brazo (1-Arm Sit Up)',                                        category:'Core',             videoUrl:'https://www.youtube.com/watch?v=Q4eVlT5YSiU'},
  'def_plankleglift':   {name:'Plancha con Elevación y Abducción de Pierna (Forearm Plank Leg Lift)',    category:'Core',             videoUrl:'https://www.youtube.com/watch?v=pb7ngnx0jfw'},
  'def_vupmbpass':      {name:'Abdominales en V con Balón Medicinal (V-Up with MB Pass)',                 category:'Core',             videoUrl:'https://www.youtube.com/watch?v=fhFA6Qyrx_o'},
  'def_hiplankabduc':   {name:'Plancha Lateral Alta con Abducción (High Lateral Plank w/ Abduction)',    category:'Core',             videoUrl:'https://www.youtube.com/watch?v=36H_NCf38Lo'},
  'def_supineplank':    {name:'Plancha Supina Baja (Supine Plank - Low)',                                 category:'Core',             videoUrl:'https://www.youtube.com/watch?v=IUj698QvWO0'},
  'def_lathiplank':     {name:'Plancha Lateral Alta (Lateral High Plank)',                                category:'Core',             videoUrl:'https://www.youtube.com/watch?v=xH7BZ68YACE'},
  'def_antilatlowplank':{name:'Plancha Lateral Baja - Antiflexión Lateral (Anti-Lateral Flexion)',       category:'Core',             videoUrl:'https://www.youtube.com/watch?v=54RFCycIB_I'},
  'def_1legglutebiso':  {name:'Puente de Glúteos Isométrico a una Pierna con Palanca Larga (1-Leg Glute Bridge Iso)', category:'Core', videoUrl:'https://www.youtube.com/watch?v=UxvojHqF7yk'},
  'def_1armcarry':      {name:'Farmer Walk a un Brazo (1-Arm Suitcase Carry)',                           category:'Core',             videoUrl:'https://www.youtube.com/watch?v=DKlfJRfTuJE'},
  'def_2kbfrontrack':   {name:'Farmer Walk Frontal con Dos KB (Front Rack 2-KB Carry)',                  category:'Core',             videoUrl:'https://www.youtube.com/watch?v=s-SSrvs7PIk'},
  'def_1kbfrontrack':   {name:'Farmer Walk Frontal con Una KB (Front Rack 1-KB Carry)',                  category:'Core',             videoUrl:'https://www.youtube.com/watch?v=08W-FtyfRdQ'},
  'def_kbzerchcarry':   {name:'Farmer Walk Zercher KB (KB Zercher Carry)',                               category:'Core',             videoUrl:'https://www.youtube.com/watch?v=dh7UnuAXAAM'},
  'def_ohkbcarry':      {name:'Farmer Walk OH con KB (1-Arm Statue of Liberty KB Carry)',                category:'Core',             videoUrl:'https://www.youtube.com/watch?v=C8FIZ9CcpqI'},
  'def_offset2kbcarry': {name:'Farmer Walk Asimétrica Desfasada con 2 KB (Offset Carry)',               category:'Core',             videoUrl:'https://www.youtube.com/watch?v=lWyj8wHoO1I'},
  'def_sbzerchcarry':   {name:'Farmer Walk Zercher con Saco de Arena (Zercher Sandbag Carry)',           category:'Core',             videoUrl:'https://www.youtube.com/watch?v=r5OU1GLf_lk'},
  'def_kbbottomsupcarry':{name:'Farmer Walk KB invertida (Bottoms-Up KB Carry)',                         category:'Core',             videoUrl:'https://www.youtube.com/watch?v=NXA_wjmtTE8'},
  // ── Movilidad / Tren superior ─────────────────────────────────
  'def_bandwallslide':  {name:'Wall slides con miniband (Standing Banded Wall Slides)',                  category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/Fs9BvPrQaIo'},
  'def_wallclocks':     {name:'Relojes en Pared de Pie con Banda (Standing Wall Clocks)',                category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/p7oIoQSQwhE'},
  'def_slcalfpu':       {name:'Elevación de gemelos a una pierna en plancha (Push Up Position SL Calf Raise)', category:'Tren inferior', videoUrl:'https://www.youtube.com/shorts/756O0s_N_SM'},
  'def_quadhamiso':     {name:'Isométrico de Isquiotibiales en Cuadrupedia (Quad Position Hamstring Hold)', category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/FdhS4J49NHc'},
  'def_firehydrant':    {name:'Movilidad en Cuadrupedia (Quad Position Fire Hydrants)',                  category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/CHFufEILvEc'},
  'def_quadlatlegraise':{name:'Elevación Lateral en Cuadrupedia (Quad Position Lateral Straight Leg Raise)', category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/3wfsBjFOlkg'},
  'def_calfr21':        {name:'Elevación de gemelos 2 arriba 1 abajo (Calf Raise 2 Up 1 Down)',         category:'Tren inferior',    videoUrl:'https://www.youtube.com/shorts/sl6fwybAXr4'},
  'def_slstandclocks':  {name:'Relojes a una Pierna de Pie (Standing Single Leg Clocks)',               category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/sRclj8N5mMY'},
  'def_proneiytw':      {name:'I, Y, T, W en Prono (Prone I, Y, T, W\'s)',                              category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/AWQ9zmSMboQ'},
  'def_proneswim':      {name:'Nadadores en Prono (Prone Swimmers)',                                     category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/O-9I4R49Jqw'},
  'def_scappushup':     {name:'Push ups Escapulares (Scap Push-Ups)',                                   category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/UFHpYbmymJQ'},
  'def_butterflyglute': {name:'Puente de Glúteos Mariposa (Butterfly Glute Bridge)',                    category:'Tren inferior',          videoUrl:'https://www.youtube.com/shorts/ct7W0E-hXG0'},
  'def_lacrossepec':    {name:'Liberación de Pectoral con Pelota de Lacrosse (Lacrosse Ball Pec)',      category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/0Qdf5t7t8Y4'},
  'def_frlats':         {name:'Foam Roller Dorsales (Foam Roll Lats)',                                  category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/UtjqbXkMX4g'},
  'def_frback':         {name:'Foam Roller Espalda (Foam Roll Back)',                                   category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/3FqinBKwNzs'},
  'def_frquad':         {name:'Foam Roller Cuádriceps (Foam Roll Quad)',                                category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/6ANT_OiLeMU'},
  'def_frcalf':         {name:'Foam Roller Gemelos (Foam Roll Calf)',                                   category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/Lx2LCDZ96Sk'},
  'def_frham':          {name:'Foam Roller Isquiotibiales (Foam Roll Hamstring)',                       category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/yRn0U6TpdKU'},
  'def_frglute':        {name:'Foam Roller Glúteos (Foam Roll Glute)',                                  category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/Koq_T_9MEio'},
  'def_rollovervsit':   {name:'Rolido Atrás a sentarse V (Rollover to V Sit)',                          category:'Movilidad / Elongación', videoUrl:'https://www.youtube.com/shorts/a_NTTStggcI'},
  // ── Tren superior — hombros / landmine ────────────────────────
  'def_dbfrontraise':   {name:'Vuelos Frontales con Mancuernas (DB Front Raise)',                       category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/bODZ3JyMQBM'},
  'def_dbbentflies':    {name:'Vuelos Posteriores Inclinados con Mancuernas (DB Bent Over Flies)',      category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/8_k3j1GDmdY'},
  'def_dbohaltlock':    {name:'Press de Hombros Alterno con Mancuernas (Standing 2-DB Alt. Lockout)',   category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/ryrzIQ3gIyc'},
  'def_seatedsaohp':    {name:'Press de Hombros Sentado a un Brazo con Mancuerna (Seated DB SA OHP)',  category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/czRSaYwIZsw'},
  'def_curltopress':    {name:'Curl de Bíceps a Press de Hombros con Mancuernas (DB Curl to OHP)',     category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/VkDqXIyzM3E'},
  'def_lmhkpress':      {name:'Press Landmine a un Brazo en Media Rodilla (1/2 Kneel SA Landmine Press)', category:'Tren superior',       videoUrl:'https://www.youtube.com/shorts/F51eoyE0eRI'},
  'def_lmsplitpress':   {name:'Press Landmine a un Brazo en Split (Split-Stance SA Landmine Press)',   category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/XoeLztfQ4a4'},
  'def_lmsapress':      {name:'Press Landmine a un Brazo (Standing SA Landmine Press)',                 category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/WdbjoLSp7_k'},
  'def_lmsarow':        {name:'Remo Landmine Inclinado a un Brazo (SA Landmine Bent Over Row)',         category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/qKf_9iRReHc'},
  // ── Banda / TRX ───────────────────────────────────────────────
  'def_bandlatwalk':    {name:'Caminatas Laterales con Minibanda (Lateral Mini Band Walks)',            category:'Tren inferior',          videoUrl:'https://www.youtube.com/shorts/8GQXrETbgOo'},
  'def_bandsquat':      {name:'Sentadillas con Minibanda (Squats with Mini Band)',                      category:'Tren inferior',          videoUrl:'https://www.youtube.com/shorts/--_OsBMNW4c'},
  'def_bandpullapart':  {name:'Aperturas de Banda al Frente (Band Pull Apart - Front)',                 category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/VSeGyrFewkE'},
  'def_chestsupdrow':   {name:'Remo con Mancuernas Apoyado en Banco (Chest-Supported DB Row)',         category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/pm-P9oUWk7g'},
  'def_trxpushup2':     {name:'Push Ups en TRX (TRX Push-Ups)',                                        category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/yuhlD2Htb88'},
  'def_trxsarowreach':  {name:'Remo a un Brazo con Alcance en TRX (TRX SA Row with Reach)',            category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/dLw_6BbW0n8'},
  'def_trxirow':        {name:'Remo en I en TRX (TRX I\'s)',                                           category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/XoX4bcfH7cw'},
  'def_trxyrow':        {name:'Remo en Y en TRX (TRX Y\'s)',                                           category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/A_lXN_9yQjc'},
  'def_trxwrow':        {name:'Remo en W en TRX (TRX W\'s)',                                           category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/vs4IzE5ie_U'},
  'def_trxsarow':       {name:'Remo a un Brazo en TRX (TRX SA Row)',                                   category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/aoPR_O7ivRs'},
  // ── Press / Push-Up variantes / Core crawl ────────────────────
  'def_sainclinedbbp':  {name:'Press de Banca Inclinado a un Brazo con Mancuerna (SA Incline DB Bench Press)', category:'Tren superior',  videoUrl:'https://www.youtube.com/shorts/J9oi1O7w3CA'},
  'def_altlockincdbp':  {name:'Press de Banca Inclinado Bloqueo Alterno con Mancuernas (Alt. Lockout Incline DB)', category:'Tren superior', videoUrl:'https://www.youtube.com/shorts/0_cxD4EGtow'},
  'def_sadbfloorpress': {name:'Press de Banca Plano a un Brazo con Mancuerna (SA DB Bench Press)',            category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/Cs2uNF-jW5s'},
  'def_altlockdbp':     {name:'Press de Banca Plano Bloqueo Alterno con Mancuernas (Alt. Lockout DB Bench)',  category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/69M_A29QMe4'},
  'def_feetelevpush':   {name:'Push Ups con Pies Elevados (Feet-Elevated Push-Ups)',                          category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/fTy5dlnIu-o'},
  'def_handelevpush':   {name:'Push Up con Manos Elevadas (Hand-Elevated Push-Up)',                           category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/gzatmf3OUvU'},
  'def_bearcrawlshouldertap':{name:'Tap de Hombros en Bear Crawl (Crawling Position Shoulder Taps)',         category:'Core',                   videoUrl:'https://www.youtube.com/shorts/15-xlfNEAwY'},
  'def_pushupshouldertap':   {name:'Tap de Hombros en Push Up (Push-Up Position Shoulder Taps)',             category:'Core',                   videoUrl:'https://www.youtube.com/shorts/jrXfvy1b1QU'},
  'def_bearcrawlkbdrag':     {name:'Arrastres KB en Bear Crawl (Crawling Position KB Pull Throughs)',        category:'Core',                   videoUrl:'https://www.youtube.com/shorts/79fGG5HDlfo'},
  'def_pushupdrag':          {name:'Arrastres KB en Push Up (Push-Up Position KB Pull Throughs)',            category:'Core',                   videoUrl:'https://www.youtube.com/shorts/BhxK9Y78yPk'},
  'def_kbhalo':         {name:'Halos con Pesa Rusa (KB Halos)',                                               category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/eA4vICB3tqo'},
  // ── Fitball / Swiss Ball ──────────────────────────────────────
  'def_sbodysaw':       {name:'Plancha Fitball con Movimiento de Sierra (Swiss Ball Body Saw)',              category:'Core',                   videoUrl:'https://www.youtube.com/shorts/LebhgK0NytY'},
  'def_sbpushup':       {name:'Flexiones de Brazos sobre Fitball (Push-Ups on Swiss Ball)',                  category:'Tren superior',          videoUrl:'https://www.youtube.com/shorts/mQ8N9ZZNEXo'},
  'def_sbsideplank':    {name:'Plancha Lateral Isométrica en Fitball sin Apoyo (Swiss Ball Side Plank Hold)', category:'Core',                  videoUrl:'https://www.youtube.com/shorts/mQ8N9ZZNEXo'},
  'def_sbsideplankhand':{name:'Plancha Lateral en Fitball con Apoyo de Mano (Swiss Ball Side Plank - Hand Supported)', category:'Core',         videoUrl:'https://www.youtube.com/shorts/vfz2CNz7c0o'},
  'def_sbkneestochest': {name:'Flexión de Rodillas al Pecho en Fitball (Swiss Ball Knees to Chest)',         category:'Core',                   videoUrl:'https://www.youtube.com/shorts/tw49_A9TWJg'},
  'def_sbpike':         {name:'Flexión de Cadera en Fitball (Swiss Ball Pikes)',                             category:'Core',                   videoUrl:'https://www.youtube.com/shorts/LoFpEFrEk0s'},
  'def_sbfeetkicks':    {name:'Patadas en Plancha con Pies en Fitball (Swiss Ball Feet on Ball Kicks)',      category:'Core',                   videoUrl:'https://www.youtube.com/shorts/BgA3qPiaum0'},
  'def_sbstirpot':      {name:'Fitball Revolver la Olla (Swiss Ball Front Plank Stir the Pot)',              category:'Core',                   videoUrl:'https://www.youtube.com/shorts/1C4MxyLlA1g'},
  'def_sbarmlift':      {name:'Plancha Fitball con Elevación de Brazos (Swiss Ball Front Plank Arm Lifts)',  category:'Core',                   videoUrl:'https://www.youtube.com/shorts/WfcPv-xFH_M'},
  'def_sbpurollout':    {name:'Rollout Fitball desde Posición de Flexión (Push-Up Position Swiss Ball Rollout)', category:'Core',              videoUrl:'https://www.youtube.com/shorts/VK5nFecbZTc'},
  'def_sbplankrollout': {name:'Rollout en Plancha sobre Fitball (Swiss Ball Front Plank Rollout)',           category:'Core',                   videoUrl:'https://www.youtube.com/shorts/873-UKojMz4'},
};

// ── Default program templates (available to all users) ────────
const DEFAULT_PROGRAMS = {
  'tpl_recomp3d': {
    name: 'Recomposición — 3 Días Fuerza',
    createdAt: 0,
    days: {
      'tpl_d1': {
        name: 'Día 1 — Full Body A',
        order: 0,
        blocks: {
          'tpl_d1_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_d1_b1_i1': {exId:'def_squatstand', exName:'Sentadilla a extensión',                        order:0, sets:{'0':{type:'reps',reps:'8', weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8', weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d1_b1_i2': {exId:'def_revlungerot',exName:'Estocada reversa con rotación',                 order:1, sets:{'0':{type:'reps',reps:'5', weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5', weight:'',rir:'',pct:'',notes:'/lado'}}},
            'tpl_d1_b1_i3': {exId:'def_dogcobra',   exName:'Perro boca abajo a cobra con rotación',         order:2, sets:{'0':{type:'reps',reps:'5', weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'5', weight:'',rir:'',pct:'',notes:''}}},
          }},
          'tpl_d1_b2': { name:'Fuerza', type:'strength', order:1, items:{
            'tpl_d1_b2_i1': {exId:'def_sq',  exName:'Sentadilla con barra', order:0, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'75',notes:''},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'75',notes:''},'2':{type:'reps',reps:'5',weight:'',rir:'',pct:'78',notes:''},'3':{type:'reps',reps:'5',weight:'',rir:'',pct:'80',notes:''}}},
            'tpl_d1_b2_i2': {exId:'def_bp',  exName:'Press de banca plano', order:1, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_d1_b3': { name:'Hipertrofia', type:'strength', order:2, items:{
            'tpl_d1_b3_i1': {exId:'def_hipth',  exName:'Hip thrust con barra',         order:0, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d1_b3_i2': {exId:'def_dbrow',  exName:'Remo con mancuerna (DB Row)',   order:1, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_d1_b3_i3': {exId:'def_lunge',  exName:'Estocadas caminando',          order:2, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_d1_b3_i4': {exId:'def_dips',   exName:'Fondos en paralelas',          order:3, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_d1_b4': { name:'Finisher', type:'cardio', order:3, items:{
            'tpl_d1_b4_i1': {exId:'def_kbswing', exName:'Swing con pesa rusa (KB Swing)', order:0, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d1_b4_i2': {exId:'def_plank',   exName:'Plancha isométrica',            order:1, sets:{'0':{type:'time',reps:'',time:'35s',weight:'',rir:'',pct:'',notes:''},'1':{type:'time',reps:'',time:'35s',weight:'',rir:'',pct:'',notes:''},'2':{type:'time',reps:'',time:'35s',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
      'tpl_d2': {
        name: 'Día 2 — Full Body B',
        order: 1,
        blocks: {
          'tpl_d2_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_d2_b1_i1': {exId:'def_mob',        exName:'Movilidad articular guiada',                     order:0, sets:{'0':{type:'time',reps:'',time:'2:00',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d2_b1_i2': {exId:'def_staggerrdl', exName:'Calentamiento RDL escalonado (Staggered Stance RDL Warm Up)', order:1, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
            'tpl_d2_b1_i3': {exId:'def_catcow',     exName:'Postura gato-vaca (Cat-Cow)',                     order:2, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''}}},
          }},
          'tpl_d2_b2': { name:'Fuerza', type:'strength', order:1, items:{
            'tpl_d2_b2_i1': {exId:'def_dead', exName:'Peso muerto convencional', order:0, sets:{'0':{type:'reps',reps:'4',weight:'',rir:'',pct:'80',notes:''},'1':{type:'reps',reps:'4',weight:'',rir:'',pct:'80',notes:''},'2':{type:'reps',reps:'5',weight:'',rir:'',pct:'78',notes:''},'3':{type:'reps',reps:'5',weight:'',rir:'',pct:'78',notes:''}}},
            'tpl_d2_b2_i2': {exId:'def_ohp',  exName:'Press militar con barra',  order:1, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_d2_b3': { name:'Hipertrofia', type:'strength', order:2, items:{
            'tpl_d2_b3_i1': {exId:'def_latpull',  exName:'Jalón al pecho (Lat Pull Down)',           order:0, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d2_b3_i2': {exId:'def_rdl',      exName:'Peso muerto rumano',                       order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d2_b3_i3': {exId:'def_curl',     exName:'Curl de bíceps con mancuerna',             order:2, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d2_b3_i4': {exId:'def_tri',      exName:'Extensión de tríceps en polea',            order:3, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d2_b3_i5': {exId:'def_latraise', exName:'Elevaciones laterales (Lateral Raises)',   order:4, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_d2_b4': { name:'Finisher — AMRAP 10 min', type:'cardio', order:3, items:{
            'tpl_d2_b4_i1': {exId:'def_dbthr',     exName:'Thruster con mancuernas',          order:0, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d2_b4_i2': {exId:'def_mountclimb',exName:'Escaladores (Mountain Climbers)',   order:1, sets:{'0':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d2_b4_i3': {exId:'def_kbswing',   exName:'Swing con pesa rusa (KB Swing)',    order:2, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
      'tpl_d3': {
        name: 'Día 3 — Full Body C',
        order: 2,
        blocks: {
          'tpl_d3_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_d3_b1_i1': {exId:'def_foam',        exName:'Foam roller — MMII',                          order:0, sets:{'0':{type:'time',reps:'',time:'3:00',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d3_b1_i2': {exId:'def_squatstand',  exName:'Sentadilla a extensión',                      order:1, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d3_b1_i3': {exId:'def_beststretch', exName:'Rotación de estiramiento (Best Stretch Rotations)', order:2, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
          }},
          'tpl_d3_b2': { name:'Fuerza Unilateral', type:'strength', order:1, items:{
            'tpl_d3_b2_i1': {exId:'def_bblunge', exName:'Estocada con barra (Barbell Lunge)', order:0, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_d3_b2_i2': {exId:'def_row',    exName:'Remo con barra',                     order:1, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_d3_b3': { name:'Hipertrofia', type:'strength', order:2, items:{
            'tpl_d3_b3_i1': {exId:'def_dbbp',        exName:'Press de banca con mancuernas (DB Bench Press)', order:0, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d3_b3_i2': {exId:'def_seatedcabrow',exName:'Remo en polea baja sentado',                    order:1, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d3_b3_i3': {exId:'def_facepull',    exName:'Tirón al rostro en polea (Face Pull)',          order:2, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_d3_b3_i4': {exId:'def_abwheel',     exName:'Rueda abdominal (Ab Wheel)',                    order:3, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_d3_b4': { name:'Finisher — 4 rondas', type:'cardio', order:3, items:{
            'tpl_d3_b4_i1': {exId:'def_box',    exName:'Box jump',      order:0, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''},'3':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d3_b4_i2': {exId:'def_burpee', exName:'Burpee',        order:1, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_d3_b4_i3': {exId:'def_russ',   exName:'Russian twist', order:2, sets:{'0':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'3':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
    },
  },
  'tpl_bball4d': {
    name: 'Hipertrofia Básquet — 4 Días',
    createdAt: 0,
    days: {
      'tpl_bb_d1': {
        name: 'Día 1 — Tren Inferior A (Quad)',
        order: 0,
        blocks: {
          'tpl_bb_d1_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_bb_d1_b1_i1': {exId:'def_squatstand',  exName:'Sentadilla a extensión',                       order:0, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d1_b1_i2': {exId:'def_revlungerot', exName:'Estocada reversa con rotación',                order:1, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
            'tpl_bb_d1_b1_i3': {exId:'def_staggerrdl',  exName:'Calentamiento RDL escalonado (Staggered Stance RDL Warm Up)', order:2, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
          }},
          'tpl_bb_d1_b2': { name:'Fuerza', type:'strength', order:1, items:{
            'tpl_bb_d1_b2_i1': {exId:'def_sq',    exName:'Sentadilla con barra', order:0, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d1_b2_i2': {exId:'def_hipth', exName:'Hip thrust con barra', order:1, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d1_b3': { name:'Hipertrofia', type:'strength', order:2, items:{
            'tpl_bb_d1_b3_i1': {exId:'def_lunge',  exName:'Estocadas caminando',                order:0, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_bb_d1_b3_i2': {exId:'def_stepup', exName:'Step-up en caja',                   order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_bb_d1_b3_i3': {exId:'def_goblet', exName:'Sentadilla goblet con mancuerna (Goblet Squat)', order:2, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d1_b4': { name:'Prevención + Core', type:'preventive', order:3, items:{
            'tpl_bb_d1_b4_i1': {exId:'def_nordicdrop', exName:'Caída nórdica (Nordic Drops)', order:0, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'6',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d1_b4_i2': {exId:'def_plank',      exName:'Plancha isométrica',           order:1, sets:{'0':{type:'time',reps:'',time:'40s',weight:'',rir:'',pct:'',notes:''},'1':{type:'time',reps:'',time:'40s',weight:'',rir:'',pct:'',notes:''},'2':{type:'time',reps:'',time:'40s',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d1_b4_i3': {exId:'def_abwheel',    exName:'Rueda abdominal (Ab Wheel)',   order:2, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
      'tpl_bb_d2': {
        name: 'Día 2 — Tren Superior A (Horizontal)',
        order: 1,
        blocks: {
          'tpl_bb_d2_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_bb_d2_b1_i1': {exId:'def_dogcobra',    exName:'Perro boca abajo a cobra con rotación', order:0, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d2_b1_i2': {exId:'def_threadneedle',exName:'Enhebrar la aguja (Thread the Needle)', order:1, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
          }},
          'tpl_bb_d2_b2': { name:'Fuerza', type:'strength', order:1, items:{
            'tpl_bb_d2_b2_i1': {exId:'def_bp',  exName:'Press de banca plano', order:0, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d2_b2_i2': {exId:'def_row', exName:'Remo con barra',       order:1, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d2_b3': { name:'Hipertrofia', type:'strength', order:2, items:{
            'tpl_bb_d2_b3_i1': {exId:'def_dbbp',        exName:'Press de banca con mancuernas (DB Bench Press)', order:0, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d2_b3_i2': {exId:'def_dbrow',       exName:'Remo con mancuerna (DB Row)',                    order:1, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_bb_d2_b3_i3': {exId:'def_dips',        exName:'Fondos en paralelas',                            order:2, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d2_b3_i4': {exId:'def_seatedcabrow',exName:'Remo en polea baja sentado',                     order:3, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d2_b4': { name:'Accesorios', type:'preventive', order:3, items:{
            'tpl_bb_d2_b4_i1': {exId:'def_facepull',  exName:'Tirón al rostro en polea (Face Pull)', order:0, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d2_b4_i2': {exId:'def_latraise',  exName:'Elevaciones laterales (Lateral Raises)', order:1, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d2_b4_i3': {exId:'def_curl',      exName:'Curl de bíceps con mancuerna',           order:2, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
      'tpl_bb_d3': {
        name: 'Día 3 — Tren Inferior B (Posterior)',
        order: 2,
        blocks: {
          'tpl_bb_d3_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_bb_d3_b1_i1': {exId:'def_foam',        exName:'Foam roller — MMII',                          order:0, sets:{'0':{type:'time',reps:'',time:'3:00',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d3_b1_i2': {exId:'def_catcow',      exName:'Postura gato-vaca (Cat-Cow)',                  order:1, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'8',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d3_b1_i3': {exId:'def_beststretch', exName:'Rotación de estiramiento (Best Stretch Rotations)', order:2, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
          }},
          'tpl_bb_d3_b2': { name:'Fuerza', type:'strength', order:1, items:{
            'tpl_bb_d3_b2_i1': {exId:'def_dead', exName:'Peso muerto convencional', order:0, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'5',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d3_b2_i2': {exId:'def_rdl',  exName:'Peso muerto rumano',       order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d3_b3': { name:'Hipertrofia Unilateral', type:'strength', order:2, items:{
            'tpl_bb_d3_b3_i1': {exId:'def_bblunge',   exName:'Estocada con barra (Barbell Lunge)',                    order:0, sets:{'0':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_bb_d3_b3_i2': {exId:'def_db1legrdl', exName:'Peso muerto rumano unilateral con mancuerna (DB One-Leg RDL)', order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'},'2':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:'/lado'}}},
            'tpl_bb_d3_b3_i3': {exId:'def_pullthrough',exName:'Pull through (Tracción entre piernas)',                 order:2, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d3_b4': { name:'Prevención + Core', type:'preventive', order:3, items:{
            'tpl_bb_d3_b4_i1': {exId:'def_nordic',    exName:'Nordic curl',                              order:0, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'6',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d3_b4_i2': {exId:'def_splitchop', exName:'Chop en posición de estocada (Split Stance Chop)', order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:'/lado'},'2':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:'/lado'}}},
            'tpl_bb_d3_b4_i3': {exId:'def_russ',      exName:'Russian twist',                            order:2, sets:{'0':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'20',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
      'tpl_bb_d4': {
        name: 'Día 4 — Tren Superior B (Vertical)',
        order: 3,
        blocks: {
          'tpl_bb_d4_b1': { name:'Calentamiento', type:'warmup', order:0, items:{
            'tpl_bb_d4_b1_i1': {exId:'def_mob',         exName:'Movilidad articular guiada',              order:0, sets:{'0':{type:'time',reps:'',time:'2:00',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d4_b1_i2': {exId:'def_threadneedle',exName:'Enhebrar la aguja (Thread the Needle)',   order:1, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'},'1':{type:'reps',reps:'5',weight:'',rir:'',pct:'',notes:'/lado'}}},
          }},
          'tpl_bb_d4_b2': { name:'Fuerza', type:'strength', order:1, items:{
            'tpl_bb_d4_b2_i1': {exId:'def_pull', exName:'Dominadas / Pull-up',      order:0, sets:{'0':{type:'reps',reps:'5',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d4_b2_i2': {exId:'def_ohp',  exName:'Press militar con barra', order:1, sets:{'0':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'6',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''},'3':{type:'reps',reps:'8',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d4_b3': { name:'Hipertrofia', type:'strength', order:2, items:{
            'tpl_bb_d4_b3_i1': {exId:'def_latpull',   exName:'Jalón al pecho (Lat Pull Down)',                        order:0, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d4_b3_i2': {exId:'def_dbohp',    exName:'Press militar con mancuernas (DB Military Press)',       order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d4_b3_i3': {exId:'def_dbbentrow',exName:'Remo con mancuernas inclinado (Dual DB Bent Over Row)',  order:2, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
            'tpl_bb_d4_b3_i4': {exId:'def_arnold',   exName:'Press Arnold sentado con mancuerna (Arnold Press)',      order:3, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'2',pct:'',notes:''}}},
          }},
          'tpl_bb_d4_b4': { name:'Accesorios', type:'preventive', order:3, items:{
            'tpl_bb_d4_b4_i1': {exId:'def_facepull', exName:'Tirón al rostro en polea (Face Pull)', order:0, sets:{'0':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'15',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d4_b4_i2': {exId:'def_zottman',  exName:'Curl Zottman (Zottman Curl)',           order:1, sets:{'0':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'10',weight:'',rir:'',pct:'',notes:''}}},
            'tpl_bb_d4_b4_i3': {exId:'def_tri',      exName:'Extensión de tríceps en polea',         order:2, sets:{'0':{type:'reps',reps:'12',weight:'',rir:'',pct:'',notes:''},'1':{type:'reps',reps:'12',weight:'',rir:'',pct:'',notes:''},'2':{type:'reps',reps:'12',weight:'',rir:'',pct:'',notes:''}}},
          }},
        },
      },
    },
  },
};
